<!DOCTYPE html>
<html lang="en">

<!-- The header of the webpage. Contains the meta tags and Title -->
<head>
    <!-- Metadata tags -->
    <meta charset="UTF-8">
    <meta name="description" content="Project Part 1 jobs.html Page">
    <meta name="keywords" content="HTML5, Forms, Group Project, Job Application">
    <meta name="author" content="Ryan Weber">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Job Descriptions</title>

    <link rel = "stylesheet" href = "styles/style.css">
    <link rel="icon" type="image/x-icon" href="images/tab_icon.png">
</head>

<body>
    <header>
        <?php
            $page_title = "Job Descriptions"; // Set the page title
            include 'header.inc'; // Include the header file
        ?>
        <?php include 'nav.inc' ?> <!--Include Navigation Bar-->
        <br>
    </header>

    <!-- Begin the main content of the web page -->
    <main>
        <p id = "job_prompt">Here, you can view our amazing job descriptions!<br>Browse and view each one for its required skills, and an overview of the work you will be undertaking!<br>Also see appropriate annual salaries, and other important information.</p>
        <aside id = "job_aside">Use the <a href="apply.php" title="Apply">Apply</a> page to apply for a job.<br>You will need to use the reference code shown in the description of the job you would like to apply for.</aside><!--This might not need to be a float-->
        <br>

        <!--jobs in sections-->
        <!-- Cant use the name section as a class -->
        <div class = "job_description_box">
            <section class = "job_description_left">
                <h1 class = "job_title">Data Analyst</h1>
                <br>
                <p>
                    As a Data Analyst for OpenSOS, you will play a critical role in supporting our mission by turning raw data into meaningful insights that drive informed decision-making. You will collaborate closely with cross-functional teams, including developers, program managers, and stakeholders, to identify, collect, and analyze data from a variety of sources. Your work will focus on multiple key areas of interest such as tracking and evaluating emerging issues with our technologies, monitoring and interpreting user interactions with our digital platforms, and exploring opportunities to enhance the overall effectiveness and efficiency of our programs and operations. In this role, you are not just analyzing numbers — you’re helping tell the story of how OpenSOS can grow, adapt, and improve through data-driven strategies.
                    <!--Description generated by ChatGPT, prompt: create a description for a Data Analyst role for a company OpenSOS-->
                </p>
                <br>

                <!--responsibilities list-->
                <h3>Key Responsibilities</h3>
                <ol>
                    <li class = "list_indent">
                        Collecting data from reliable sources
                    </li>
                    <li class = "list_indent">
                        Cleaning data and interoperating it in a meaningful way
                    </li>
                    <li class = "list_indent">
                        Presenting data in a clear way that is easy to understand
                    </li>
                </ol>
            </section>
            <!--main-->

            <!--key attributes list shifted to the right-->
            <section class = "job_description_right">
                <br> <!--I don't think this is technically aligned, perhaps change in future-->
                <h3>Key Attributes</h3>
                <ul>
                    <li class = "list_indent">
                        Essential
                        <ul>
                            <li class = "list_indent">
                                1 Year of experience as a data analyst
                            </li>
                            <li class = "list_indent">
                                A Degree in Computer Science or a related field
                            </li>
                        </ul>
                    </li>
                    <li class = "list_indent">
                        Preferred
                        <ul>
                            <li class = "list_indent">
                                Experience using Excel, Python, and SQL
                            </li>
                            <li class = "list_indent">
                                Good communication skills
                            </li>
                            <li class = "list_indent">
                                A positive attitude towards learning in the workspace and striving to improve
                            </li>
                            <li class = "list_indent">
                                Experience using various data visualization tools 
                            </li>
                        </ul>
                    </li>
                </ul>
                <br>

                <!--other info-->
                <p>Salary: $90000 - $100000 per annum</p>
                <p>Reports to: Analytics Leader</p>
                
                <br><br>
                <div class="apply_container">
                    <p class="reference_number"><em>Reference Number: H3110</em></p>
                    <a href="apply.php" class="buttons_description_box">Apply</a>
                </div>
            </section>
        </div>

        <div class = "job_description_box">
            <section class = "job_description_left">
                <h1 class = "job_title">Programmer</h1>
                <br>
                <p>
                    As a Programmer at OpenSOS, you will play a key role in the development and maintenance of our software systems. You will collaborate closely with our software development team to design, implement, and refine code for a wide range of applications that support our mission. Your responsibilities will include writing clean, efficient, and well-documented code, as well as conducting regular reviews to ensure reliability, performance, and scalability. In this role, you’ll not only contribute to building new features but also help optimize existing codebases and debug issues that arise during development or testing phases. You will be encouraged to apply best practices in software engineering and stay updated with modern programming trends to continually improve the quality of our products.
                    <!--Description generated by ChatGPT, prompt: create a description for a Programmer role for a company OpenSOS-->
                </p>
                <br>

                <!--responsibilities list-->
                <h3>Key Responsibilities</h3>
                <ol>
                    <li class = "list_indent">
                        Write clear and efficient code
                    </li>
                    <li class = "list_indent">
                        Test code to ensure reliability across different environments
                    </li>
                    <li class = "list_indent">
                        Maintain and update softwares
                    </li>
                </ol>
            </section>      

            <!--key attributes list shifted to the right-->
            <section class = "job_description_right">
                <br>
                <h3>Key Attributes</h3>
                <ul>
                    <li class = "list_indent">
                        Essential
                        <ul>
                            <li class = "list_indent">
                                1 Year of experience as a programmer
                            </li>
                            <li class = "list_indent">
                                A Degree in Computer Science or a related field
                            </li>
                        </ul>
                    </li>
                    <li class = "list_indent">
                        Preferred
                        <ul>
                            <li class = "list_indent">
                                Experience using programming languages such as c#, c++ and python
                            </li>
                            <li class = "list_indent">
                                A background of previously worked-on programs
                            </li>
                            <li class = "list_indent">
                                Good communication skills
                            </li>
                            <li class = "list_indent">
                                A positive attitude towards learning in the workspace and striving to improve
                            </li>
                        </ul>
                    </li>
                </ul>
                <br>
                <!--other info-->
                <p>Salary: $100000 - $120000 per annum</p>
                <p>Reports to: Director of Software Engineering</p>
                
                <br>
                <div class="apply_container">
                    <p class="reference_number"><em>Reference Number: T4B13</em></p>
                    <a href="apply.php" class="buttons_description_box">Apply</a>
                </div>
            </section>
        </div>

        <div class = "job_description_box">
            <section class = "job_description_left">
                <h1 class = "job_title">Front-end Web Developer</h1>
                <br>
                <p>
                    As a Front-End Web Developer at OpenSOS, you will be responsible for crafting user-facing features and interfaces that are not only visually appealing but also functional, accessible, and responsive across a variety of platforms and devices. You will collaborate closely with back-end developers, UI/UX designers, and other stakeholders to transform design mockups and functional requirements into fully responsive and interactive web pages. Your work will focus on creating seamless user experiences by writing clean, efficient, and modular HTML, CSS, and JavaScript. You will also be responsible for integrating APIs, handling data transfer securely between front-end components and back-end systems, and ensuring that security and performance standards are met across all user interactions.
                    <!--Description generated by ChatGPT, prompt: create a description for a Front-End Web Developer role for a company OpenSOS-->
                </p>
                <br>
                
                <!--responsibilities list-->
                <h3>Key Responsibilities</h3>
                <ol>
                    <li class = "list_indent">
                        Create clean UI for web pages
                    </li>
                    <li class = "list_indent">
                        Ensure websites work, and are usable in a range of different environments and with a variety of users
                    </li>
                    <li class = "list_indent">
                        Collaborate with designers and back-end developers effectively
                    </li>
                </ol>
            </section>
            
            <!--key attributes list shifted to the right-->
            <section class = "job_description_right">
                <br>
                <h3>Key Attributes</h3>
                <ul>
                    <li class = "list_indent">
                        Essential
                        <ul>
                            <li class = "list_indent">
                                1 Year of experience as a front-end developer
                            </li>
                            <li class = "list_indent">
                                A Degree in Computer Science or a related field
                            </li>
                            <li class = "list_indent">
                                Experience using HTML, CSS and JavaScript
                            </li>
                        </ul>
                    </li>
                    <li class = "list_indent">
                        Preferred
                        <ul>
                            <li class = "list_indent">
                                A background of previously worked-on web pages
                            </li>
                            <li class = "list_indent">
                                Good communication skills
                            </li>
                            <li class = "list_indent">
                                A positive attitude towards learning in the workspace and striving to improve
                            </li>
                            <li class = "list_indent">
                                Experience using frameworks such as React, Angular or Vue.js
                            </li>
                        </ul>
                    </li>
                </ul>
                <br>

                <!--other info-->
                <p>Salary: $90000 - $110000 per annum</p>
                <p>Reports to: Web development manager</p>
                
                <br><br>
                <div class="apply_container">
                    <p class="reference_number"><em>Reference Number: P1224</em></p>
                    <a href="apply.php" class="buttons_description_box">Apply</a>
                </div>
            </section>
        </div>
    </main>

    <?php include 'footer.inc' ?> <!--Include Footer-->
</body>
</html>