<?php
session_start(); // Start fresh session
require_once 'settings.php'; // Ensure this file correctly initializes $conn
?>

<!DOCTYPE html>
<html lang="en">

<!-- The header of the webpage. Contains the meta tags and Title -->
<head>
    <!-- Metadata tags -->
    <meta charset="UTF-8">
    <meta name="description" content="Project Part 1 jobs.html Page">
    <meta name="keywords" content="HTML5, Forms, Group Project, Job Application">
    <meta name="author" content="Ryan Weber">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Job Descriptions</title>

    <link rel = "stylesheet" href = "styles/style.css">
    <link rel="icon" type="image/x-icon" href="images/tab_icon.png">
</head>

<body>
    <header>
        <?php
            $page_title = "Job Descriptions"; // Set the page title
            include 'header.inc'; // Include the header file
        ?>
        <?php include 'nav.inc' ?> <!--Include Navigation Bar-->
        <br>
    </header>

    <!-- Begin the main content of the web page -->
    <main>
        <p id = "job_prompt">Here, you can view our amazing job descriptions!<br>Browse and view each one for its required skills, and an overview of the work you will be undertaking!<br>Also see appropriate annual salaries, and other important information.</p>
        <aside id = "job_aside">Use the <a href="apply.php" title="Apply">Apply</a> page to apply for a job.<br>You will need to use the reference code shown in the description of the job you would like to apply for.</aside><!--This might not need to be a float-->
        <br>

        <!--jobs in sections-->
        <!-- Cant use the name section as a class -->
        <?php
        require_once("settings.php");
        if($db_conn)
        {
            $query = "SELECT * FROM jobs";
            $result = mysqli_query($db_conn, $query);
        }

        //check query
        if($result)
        {
            //worked  
            if(mysqli_num_rows($result) > 0)
            {
                while ($row = mysqli_fetch_assoc($result))
                {
                    echo '<div class = "job_description_box">';

                    //left
                    echo '<section class = "job_description_left">';
                    echo '<h1 class = "job_title">' . $row['job_title'] . '</h1>';
                    echo '<br><p>' . $row['description'] . '</p><br>';
                    echo '<h3>Key Responsibilities</h3>';
                    echo $row['key_responsibilities'];
                    echo '</section>';

                    //right
                    echo '<section class = "job_description_right">';
                    echo '<br>';
                    echo '<h3>Key Attributes</h3>';
                    echo 'Essential';
                    echo $row['key_attributes_essential'];
                    echo 'Preferred';
                    echo $row['key_attributes_preferred'];
                    echo '<br>';
                    echo '<p>Salary: $' . $row['salary_min'] . ' - $' . $row['salary_max'] . 'per annum</p>';
                    echo '<p>Reports to: ' . $row['reports_to'] . '</p/>';
                    echo '<br><br>';
                    echo '<div class="apply_container">';
                    echo '<p class="reference_number"><em>Reference Number: ' . $row['reference_code'] . '</em></p>';

                    echo '<a href="apply.php" class="buttons_description_box">Apply</a></div></section></div>';
                }

                echo "</table>";
                echo "<br>";
                echo "<a href='search_form.php'>Search for a car</a>";
            }
            else
            {
                echo "There are no jobs to display.";
            }    
        }
        else
        {
            //didn't work
            echo "No Connection";
        }

        
        /*<div class = "job_description_box">
            <section class = "job_description_left">
                <h1 class = "job_title">Data Analyst</h1>
                <br>
                <p>
                    As a Data Analyst for OpenSOS, you will play a critical role in supporting our mission by turning raw data into meaningful insights that drive informed decision-making. You will collaborate closely with cross-functional teams, including developers, program managers, and stakeholders, to identify, collect, and analyze data from a variety of sources. Your work will focus on multiple key areas of interest such as tracking and evaluating emerging issues with our technologies, monitoring and interpreting user interactions with our digital platforms, and exploring opportunities to enhance the overall effectiveness and efficiency of our programs and operations. In this role, you are not just analyzing numbers — you’re helping tell the story of how OpenSOS can grow, adapt, and improve through data-driven strategies.
                    <!--Description generated by ChatGPT, prompt: create a description for a Data Analyst role for a company OpenSOS-->
                </p>
                <br>

                <!--responsibilities list-->
                <h3>Key Responsibilities</h3>
                <ol>
                    <li class = "list_indent">
                        Collecting data from reliable sources
                    </li>
                    <li class = "list_indent">
                        Cleaning data and interoperating it in a meaningful way
                    </li>
                    <li class = "list_indent">
                        Presenting data in a clear way that is easy to understand
                    </li>
                </ol>
            </section>
            <!--main-->

            <!--key attributes list shifted to the right-->
            <section class = "job_description_right">
                <br> <!--I don't think this is technically aligned, perhaps change in future-->
                <h3>Key Attributes</h3>
                <ul>
                    <li class = "list_indent">
                        Essential
                        <ul>
                            <li class = "list_indent">
                                1 Year of experience as a data analyst
                            </li>
                            <li class = "list_indent">
                                A Degree in Computer Science or a related field
                            </li>
                        </ul>
                    </li>
                    <li class = "list_indent">
                        Preferred
                        <ul>
                            <li class = "list_indent">
                                Experience using Excel, Python, and SQL
                            </li>
                            <li class = "list_indent">
                                Good communication skills
                            </li>
                            <li class = "list_indent">
                                A positive attitude towards learning in the workspace and striving to improve
                            </li>
                            <li class = "list_indent">
                                Experience using various data visualization tools 
                            </li>
                        </ul>
                    </li>
                </ul>
                <br>

                <!--other info-->
                <p>Salary: $90000 - $100000 per annum</p>
                <p>Reports to: Analytics Leader</p>
                
                <br><br>
                <div class="apply_container">
                    <p class="reference_number"><em>Reference Number: H3110</em></p>
                    <a href="apply.php" class="buttons_description_box">Apply</a>
                </div>
            </section>
        </div>*/?>
    </main>

    <?php include 'footer.inc' ?> <!--Include Footer-->
</body>
</html>