<!--Theme Selector Section-->
<div id="theme_selector">
  <p><strong>Please choose a theme:</strong></p>

  <input type="radio" id="original" name="theme" value="original" checked>
  <label for="original">Original</label>

  <input type="radio" id="red" name="theme" value="red">
  <label for="red">Red</label>

  <input type="radio" id="blue" name="theme" value="blue">
  <label for="blue">Blue</label>

  <input type="radio" id="yellow" name="theme" value="yellow">
  <label for="yellow">Yellow</label>
</div>
